services:
  scandai:
    image: paolini/scandai:test
#    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/scandai
      - GOOGLE_CLIENT_ID=xxxxx
#      - GOOGLE_CLIENT_SECRET=xxxxx
      - NEXTAUTH_SECRET=replace_with_your_secret
      - NEXTAUTH_URL=http://localhost:3000/api/auth
#      - ADMIN_USERNAME=admin
#      - ADMIN_PASSWORD= 
#      - SMTP_HOST=xxxxx
#      - SMTP_PORT=xxxxx
#      - SMTP_USER=xxxxx
#      - SMTP_PASSWORD=xxxxx
#      - EMAIL_FROM=xxxxx
    ports:
      - 3000:3000

    networks:
      - backend

  mongodb:
    image: mongo:7
#    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    networks:
      - backend

networks:
  backend:
